using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using SqlFu.Expressions;
using SqlFu.Internals;

namespace SqlFu
{
    public static class SqlExtensionsCommands
    {
        //[Obsolete("Use QuerySingle")]
        //public static T FirstOrDefault<T>(this IAccessDb db, string sql, params object[] args)
        //{
        //    return db.QuerySingle<T>(sql, args);
        //}

        #region Insert

        /// <summary>
        /// Inserts into database
        /// </summary>
        /// <param name="db"></param>
        /// <param name="table">Table name</param>
        /// <param name="data">Column and Values</param>
        /// <param name="idIsIdentity">By default if the object has an Id property, it's considered to be autoincremented</param>
        /// <returns></returns>
        public static LastInsertId Insert(this IAccessDb db, string table, object data, bool idIsIdentity = true)
        {
            table.MustNotBeEmpty();
            data.MustNotBeNull();
            var ti = new TableInfo(table);
            ti.AutoGenerated = idIsIdentity;
            return Insert(db, ti, data);
        }

        public static LastInsertId Insert<T>(this IAccessDb db, T data) where T : class
        {
            data.MustNotBeNull();
            return Insert(db, TableInfo.ForType(typeof (T)), data);
        }


        private static LastInsertId Insert(IAccessDb db, TableInfo ti, object data)
        {
            var p = db.Provider;
            List<object> args = null;

            var d = data.ToDictionary();
            if (ti.InsertSql == null)
            {
                var sb = new StringBuilder("Insert into");
                sb.AppendFormat(" {0} (", p.EscapeName(ti.Name));

                args = FillArgs(d, ti, p, sb);

                sb.Remove(sb.Length - 1, 1);

                sb.Append(") values(");

                for (var i = 0; i < args.Count; i++)
                {
                    sb.Append("@" + i + ",");
                }
                sb.Remove(sb.Length - 1, 1);
                sb.Append(")");
                ti.InsertSql = sb.ToString();
            }
            if (args == null)
            {
                args = FillArgs(d, ti, p);
            }

            var st = db.WithSql(ti.InsertSql, args.ToArray()) as SqlStatement;
            st.ReuseCommand = true;
            LastInsertId rez;
            try
            {
                rez = db.Provider.ExecuteInsert(st, ti.PrimaryKey);
            }
            finally
            {
                db.CloseConnection();
            }

            return rez;
        }


        private static List<object> FillArgs(IDictionary<string, object> dict, TableInfo ti, IHaveDbProvider p,
                                             StringBuilder sb = null)
        {
            var args = new List<object>();
            foreach (var col in dict)
            {
                if (col.Key == ti.PrimaryKey)
                {
                    if (ti.AutoGenerated) continue;
                }

                if (ti.Excludes.Any(n => n.Equals(col.Key, StringComparison.InvariantCulture))) continue;
                if (sb != null) sb.AppendFormat("{0},", p.EscapeName(col.Key));
                if (ti.ConvertToString.Any(t => t == col.Key))
                {
                    args.Add(col.Value.ToString());
                }
                else
                {
                    args.Add(col.Value);
                }
            }
            return args;
        }

        #endregion

        #region Update

        /// <summary>
        /// If both poco has id property and the Id arg is specified, the arg is used
        /// </summary>
        /// <param name="db"></param>
        /// <param name="table"></param>
        /// <param name="data"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        public static int Update(this IAccessDb db, string table, object data, object id = null)
        {
            var ti = new TableInfo(table);
            return Update(db, ti, data, id);
        }

        /// <summary>
        /// If both poco has id property and the Id arg is specified, the arg is used
        /// </summary>
        public static int Update<T>(this IAccessDb db, object data, object id = null)
        {
            var ti = TableInfo.ForType(typeof (T));
            return Update(db, ti, data, id);
        }
       
        public static int UpdateWhereColumn(this IAccessDb db, string tableName,object data,string colName,object columnValue)
        {
            tableName.MustNotBeEmpty();
            colName.MustNotBeEmpty();
            columnValue.MustNotBeNull();
            return Update(db, new TableInfo(tableName),data, columnValue, colName);
        }

        public static int Update<T>(this IAccessDb db, object data, Expression<Func<T, bool>> criteria)
        {
            var args = data.ToDictionary();
            var ti = TableInfo.ForType(typeof (T));
            var updater = db.Update<T>();
            foreach (var kv in args)
            {
                if (ti.PrimaryKey == kv.Value) continue;
                if (ti.Excludes.Any(d => d == kv.Key)) continue;
                updater.Set(kv.Key, kv.Value);
            }
            return updater.Where(criteria).Execute();
        }

        /// <summary>
        /// Gets update table builder
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="db"></param>
        /// <returns></returns>
        public static IBuildUpdateTable<T> Update<T>(this IAccessDb db)
        {
            return new UpdateTableBuilder<T>(db);
        }

        private static int Update(IAccessDb db, TableInfo ti, object data, object id = null,string filterColumn=null)
        {
            var sb = new StringBuilder();
            sb.AppendFormat("update {0} set", db.Provider.EscapeName(ti.Name));
            var d = data.ToDictionary();
            bool hasId = false;
            int i = 0;
            var args = new List<object>();
            foreach (var k in d)
            {
                if (k.Key == ti.PrimaryKey)
                {
                    hasId = true;
                    continue;
                }
                if (ti.Excludes.Any(c => c == k.Key)) continue;
                sb.AppendFormat(" {0}={1},", db.Provider.EscapeName(k.Key), db.Provider.ParamPrefix + i);
                if (ti.ConvertToString.Any(s => s == k.Key))
                {
                    args.Add(k.Value.ToString());
                }
                else
                {
                    args.Add(k.Value);
                }
                i++;
            }
            sb.Remove(sb.Length - 1, 1);

            if (filterColumn.IsNullOrEmpty())
            {
                filterColumn = ti.PrimaryKey;
            }

            if (id != null || hasId)
            {
                sb.AppendFormat(" where {0}={1}", db.Provider.EscapeName(filterColumn), db.Provider.ParamPrefix + i);
                hasId = true;
                if (id == null) id = d[ti.PrimaryKey];
            }

            if (hasId) args.Add(id);

            return db.ExecuteCommand(sb.ToString(), args.ToArray());
        }

        #endregion

        [Obsolete("Use DeleteFrom")]
        public static int Delete<T>(this IAccessDb db, string condition, params object[] args)
        {
            return DeleteFrom<T>(db, condition, args);
        }
        
        public static int DeleteFrom<T>(this IAccessDb db, string condition, params object[] args)
        {
            var ti = TableInfo.ForType(typeof (T));
            return
                db.ExecuteCommand(
                    string.Format("delete from {0} where {1}", db.Provider.EscapeName(ti.Name), condition), args);
        }

        public static int DeleteFrom<T>(this IAccessDb db, Expression<Func<T, bool>> criteria=null)
        {
            var builder = new ExpressionSqlBuilder<T>(db.Provider.BuilderHelper);
            builder.WriteDelete();
            if (criteria != null)
            {
                builder.Where(criteria);
            }
            return db.ExecuteCommand(builder.ToString(), builder.Parameters.ToArray());
        }
    }
}