using System;

namespace SqlFu
{
    [AttributeUsage(AttributeTargets.Class)]
    public class TableAttribute:Attribute
    {
        public string Name { get; set; }
        /// <summary>
        /// default is Id
        /// </summary>
        public string PrimaryKey { get; set; }
        /// <summary>
        /// defaults is true
        /// </summary>
        public bool AutoGenerated { get; set; }

        public TableAttribute(string name)
        {
            name.MustNotBeEmpty();
            Name = name;
            PrimaryKey = "Id";
            AutoGenerated = true;
        }
    }
}