using System;
using SqlFu.DDL;

namespace SqlFu
{
    [AttributeUsage(AttributeTargets.Class)]
    public class TableAttribute : Attribute
    {
        public string Name { get; set; }

        /// <summary>
        /// Primary key name
        /// Default is Id
        /// </summary>
        public string PrimaryKey { get; set; }

        /// <summary>
        /// Gets or sets if the primary key is autogenerated (autoincrement,identity) by the database
        /// Used by inserts only
        /// Default is true
        /// </summary>
        public bool AutoGenerated { get; set; }

        public IfTableExists CreationOptions { get; set; }

        public TableAttribute(string name)
        {
            name.MustNotBeEmpty();
            Name = name;
            PrimaryKey = "Id";
            AutoGenerated = true;
        }
    }
}